package GUI;

import Code.Fracture;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CalcGUI {
    public JPanel panelMain;
    private JButton setInputDenominatorButton;
    private JButton setInputNumeratorButton;
    private JTextField setInputNumeratorTextField;
    private JTextField setInputDenominatorTextField;
    private JTextField OutputNumeratorTextField;
    private JButton setCalcFractureReciprocalButton;
    private JTextField OutputDenominatorTextField;
    private JTextField setExpandValueTextField;
    private JButton setExpandButton;
    private JTextField setShortenValueTextField;
    private JButton setShortenButton;
    private JTextField OutputDecimalNumberTextField;
    private JButton setShortCompletleyButton;

    Fracture fracture1 = new Fracture(1, 1);

    public CalcGUI() {
        setInputNumeratorButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fracture1.setNumerator(Integer.parseInt(setInputNumeratorTextField.getText()));
                OutputNumeratorTextField.setText(String.valueOf(fracture1.getNumerator()));
                OutputDenominatorTextField.setText(String.valueOf(fracture1.getDenominator()));
                OutputDecimalNumberTextField.setText(String.valueOf(fracture1.getDecimal()));
            }
        });
        setInputDenominatorButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fracture1.setDenominator(Integer.parseInt(setInputDenominatorTextField.getText()));
                OutputNumeratorTextField.setText(String.valueOf(fracture1.getNumerator()));
                OutputDenominatorTextField.setText(String.valueOf(fracture1.getDenominator()));
                OutputDecimalNumberTextField.setText(String.valueOf(fracture1.getDecimal()));
            }
        });
        setExpandButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fracture1.expand(Integer.parseInt(setExpandValueTextField.getText()));
                OutputNumeratorTextField.setText(String.valueOf(fracture1.getNumerator()));
                OutputDenominatorTextField.setText(String.valueOf(fracture1.getDenominator()));
                OutputDecimalNumberTextField.setText(String.valueOf(fracture1.getDecimal()));
            }
        });
        setShortenButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fracture1.shorten(Integer.parseInt(setShortenValueTextField.getText()));
                OutputNumeratorTextField.setText(String.valueOf(fracture1.getNumerator()));
                OutputDenominatorTextField.setText(String.valueOf(fracture1.getDenominator()));
                OutputDecimalNumberTextField.setText(String.valueOf(fracture1.getDecimal()));
            }
        });

        setCalcFractureReciprocalButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fracture1.reciprocal();
                OutputNumeratorTextField.setText(String.valueOf(fracture1.getNumerator()));
                OutputDenominatorTextField.setText(String.valueOf(fracture1.getDenominator()));
                OutputDecimalNumberTextField.setText(String.valueOf(fracture1.getDecimal()));
            }
        });
        setShortCompletleyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fracture1.shortenCompleteley();
                OutputNumeratorTextField.setText(String.valueOf(fracture1.getNumerator()));
                OutputDenominatorTextField.setText(String.valueOf(fracture1.getDenominator()));
                OutputDecimalNumberTextField.setText(String.valueOf(fracture1.getDecimal()));
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridBagLayout());
        panelMain.setEnabled(true);
        setInputDenominatorTextField = new JTextField();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setInputDenominatorTextField, gbc);
        setInputNumeratorTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setInputNumeratorTextField, gbc);
        setInputDenominatorButton = new JButton();
        setInputDenominatorButton.setText("Set Denominator");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setInputDenominatorButton, gbc);
        setInputNumeratorButton = new JButton();
        setInputNumeratorButton.setText("Set Numerator");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setInputNumeratorButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer2, gbc);
        setCalcFractureReciprocalButton = new JButton();
        setCalcFractureReciprocalButton.setText("Calc Reciprocal");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setCalcFractureReciprocalButton, gbc);
        OutputNumeratorTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 10;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(OutputNumeratorTextField, gbc);
        OutputDenominatorTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 12;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(OutputDenominatorTextField, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelMain.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer7, gbc);
        setExpandValueTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setExpandValueTextField, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(spacer9, gbc);
        setExpandButton = new JButton();
        setExpandButton.setText("Set Expand");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setExpandButton, gbc);
        setShortenValueTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setShortenValueTextField, gbc);
        setShortenButton = new JButton();
        setShortenButton.setText("Set Shorten");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setShortenButton, gbc);
        OutputDecimalNumberTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 13;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(OutputDecimalNumberTextField, gbc);
        setShortCompletleyButton = new JButton();
        setShortCompletleyButton.setText("Short Completley");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelMain.add(setShortCompletleyButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
